# Generated by Django 5.2.7 on 2025-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='書名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
            ],
        ),
    ]
